### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by agupta94** [rchukh/presto-querylog#14]
Could you please make this compatible with java 11?

**Comment by rchukh** [comment]
Yes, I think that it makes sense to update it to JDK 11+ since Presto recently (a few days ago) moved they product tests to JDK 11.
Also, in the latest [326](https://prestosql.io/docs/current/release/release-326.html) release, it is now  possible to use JDK11 with Presto RPM.

I'll try to take a look in the next few days.

**Comment by rchukh** [comment]
Done in https://github.com/rchukh/presto-querylog/pull/15
Available in 0.3 version - https://github.com/rchukh/presto-querylog/releases/tag/0.3

**Comment by rchukh** [comment]
Just to be clear - it should have been compatible with JDK 11 before as well.
At least according to Travis - https://travis-ci.org/rchukh/presto-querylog/jobs/568324696

Now it **requires** JDK 11 and I have checked that it actually works with Presto running on JDK 11.
